places/config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :users
  
  post '/users/add_place' => 'users#add_place'
end

places/app/models/place.rb
class Place < ApplicationRecord
    has_many :user_places
    has_many :users, through: :user_places   
end

places/app/models/user.rb
class User < ApplicationRecord
    has_many :user_places
    has_many :places, through: :user_places
end

places/app/models/user_place.rb
class UserPlace < ApplicationRecord
    belongs_to :user
    belongs_to :place
end

places/app/controllers/places_controller.rb
class PlacesController < ApplicationController
    
    def index
        @places = Place.all
    end
    
    def show
        @place = Place.find(params[:id])
    end
    
    def new
        @place = Place.new
    end
    
    def create
        @place = Place.new
        @place.name = params[:place][:name]
        @place.picture = params[:place][:picture]
        @place.description = params[:place][:description]
        @place.save
        redirect_to '/places'
    end
    
    def edit
        @place = Place.find(params[:id])
    end
    
    def update
        @place = Place.find(params[:id])
        @place.name = params[:place][:name]
        @place.picture = params[:place][:picture]
        @place.description = params[:place][:description]
        @place.save
        redirect_to '/places'
    end
    
    def delete
    end
    
end

places/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
        @places = Place.all
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new
        @user.first_name = params[:user][:first_name]
        @user.last_name = params[:user][:last_name]
        @user.email = params[:user][:email]
        @user.picture = params[:user][:picture]
        @user.save
        redirect_to '/users'
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        @user.first_name = params[:user][:first_name]
        @user.last_name = params[:user][:last_name]
        @user.email = params[:user][:email]
        @user.picture = params[:user][:picture]
        @user.save
        redirect_to '/users'
    end

    def delete
    end
    
    def add_place
        user = User.find(params[:user_id])
        user_place = UserPlace.new
        user_place.user_id = params[:user_id]
        user_place.place_id = params[:place_id]
        user_place.save
        redirect_to user_path(user)
    end

end

places/app/helpers/places_helper.rb
module PlacesHelper
end

places/app/helpers/users_helper.rb
module UsersHelper
end

places/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Places</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

places/app/views/places/edit.html.erb
<%= form_for @place do |f| %>
    
    <div>
        <%= f.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
        <%= f.text_field :picture, placeholder: 'Picture' %>
    </div>
    <div>
        <%= f.text_area :description, placeholder: 'Description' %>
    </div>
    <div>
        <%= f.submit 'Add' %>
    </div>

<% end %>

places/app/views/places/index.html.erb
<%= link_to 'New', new_place_path %>

<% @places.each do |p|%>
    
    <div class="place">    
    
        <h2><%= p.name %></h2>
        
        <img src="<%= p.picture %>" height="100">
    
        <p><%= p.description %></p>
        
        <%= link_to 'Edit', edit_place_path(p.id) %>
        
        <%= link_to 'Show', place_path(p.id) %>
        
    </div>

<% end %>

places/app/views/places/new.html.erb
<%= form_for @place do |f| %>
    
    <div>
        <%= f.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
        <%= f.text_field :picture, placeholder: 'Picture' %>
    </div>
    <div>
        <%= f.text_area :description, placeholder: 'Description' %>
    </div>
    <div>
        <%= f.submit 'Add' %>
    </div>

<% end %>

places/app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<h2> Visitors: </h2>

<% @place.users.each do |user| %>

<div>
    <h5> <%= user.first_name %> , <%= user.last_name %></h5>
    <img src="<%= user.picture %>"height="100">
</div>

<% end %>

places/app/views/users/edit.html.erb
<%= form_for @user do |f| %>
    
    <div>
        <%= f.text_field :first_name, placeholder: 'First Name' %>
    </div>
    <div>
        <%= f.text_field :last_name, placeholder: 'Last Name' %>
    </div>
    <div>
        <%= f.text_field :email, placeholder: 'Email' %>
    </div>
    <div>
        <%= f.text_field :picture, placeholder: 'Picture' %>
    </div>
    <div>
        <%= f.submit 'Add' %>
    </div>

<% end %>

places/app/views/users/index.html.erb
<%= link_to 'New' , new_user_path %>

<% @users.each do |user| %>
<div>
    <h4><%= user.first_name %></h4>
    <p><%= user.email %></p>
    <img src="<%= user.picture %>" height="100">
    <%= link_to 'Edit', edit_user_path(user)%>
    <%= link_to 'Show', user_path(user) %>
</div>

<% end %>

places/app/views/users/new.html.erb
<%= form_for @user do |f| %>
    
    <div>
        <%= f.text_field :first_name, placeholder: 'First Name' %>
    </div>
    <div>
        <%= f.text_field :last_name, placeholder: 'Last Name' %>
    </div>
    <div>
        <%= f.text_field :email, placeholder: 'Email' %>
    </div>
    <div>
        <%= f.text_field :picture, placeholder: 'Picture' %>
    </div>
    <div>
        <%= f.submit 'Add' %>
    </div>

<% end %>

places/app/views/users/show.html.erb
<h1><%= @user.first_name %>, <%= @user.last_name %></h1>

<%= form_tag '/users/add_place' do %>
    <%= hidden_field_tag 'user_id', @user.id %>
    <%= select_tag 'place_id', options_from_collection_for_select(@places, :id, :name ) %>
    <%= submit_tag 'Add' %>

<% end %>

<h2> Visited </h2>
<% @user.places.each do |place| %>

<div>
    <h5> <%= place.name %></h5>
    <img src="<%= place.picture %>"height="100">
</div>